# This is a basic workflow to help you get started with Actions

name: Build and push the tagged build to production

# Controls when the action will run. Triggers the workflow on push request
# for specific tags
on:
  push:
    tags:
      - 'v*'


# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build_push_image"
  build_push_image:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      
      - name: Fetch latest version
        id: fetch_version
        run: echo ::set-output name=TAG::${GITHUB_REF#refs/tags/}
        
      - name: Set up Buildx
        uses: docker/setup-buildx-action@v1
        
      - name: Docker Login
        # You may pin to the exact commit or the version.
        # uses: docker/login-action@465a07811f14bebb1938fbed4728c6a1ff8901fc
        uses: docker/login-action@v2.2.0
        with:
          # Server address of Docker registry. If not set then will default to Docker Hub
          registry: ${{ secrets.ACR_NAME }}
          # Username used to log against the Docker registry
          username: ${{ secrets.ACR_LOGIN }}
          # Password or personal access token used to log against the Docker registry
          password: ${{ secrets.ACR_PASSWORD }}
               
      - name: Build and push production images
        # You may pin to the exact commit or the version.
        # uses: docker/build-push-action@2eb1c1961a95fc15694676618e422e8ba1d63825
        uses: docker/build-push-action@v4.1.1
        with:
          repository: contoso-website
          context: .
          push: true
          tags: ${{secrets.ACR_NAME}}/contoso-website:latest,${{secrets.ACR_NAME}}/contoso-website:${{ steps.fetch_version.outputs.TAG }}
